name: "Multi Event Pipeline"

on:
    push:
        branches:
            - master







jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
            - name: "Running on master push"
              run: echo "Running on master push"
            