name: "Multi Event Pipeline"

on:
    push:
        branches:
            - master
            - test_branch
    pull_request:
        branches:
            -master







jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
            - name: "Running on master/test_branch push"
              run: echo "Running on master/test_branch push"
    on-pull-request:
        runs-on: ubuntu-latest
        steps:
            - name: "Running on master pull"
              run: echo "Running on master pull"            